source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.1'
gem 'protected_attributes' #remove this after 351 and do it right
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '>= 3.2'
gem 'bootstrap-sass', '~> 3.1.1'
				
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
# gem 'coffee-rails', '~> 4.0.0' #Alex doesn't know how to use CoffeeScript
gem 'bcrypt-ruby', :require=>'bcrypt'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes

# Use JsRoutes so named routes in Rails are available in JS
gem 'js-routes'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'jquery-ui-rails'
gem 'fullcalendar-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# gem 'tudusched', :path => '../prototypes/tudusched'

group :production do
  gem 'pg', '0.15.1'
  gem 'rails_12factor', '0.0.2'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
